server:
  port: 9030

spring:
  application:
    name: administrator-service
  datasource:
    url: jdbc:postgresql://ssh.basicdeploy.com:5432/bd_u_cc6d81ab11b5?sslmode=disable
    username: bd_u_cc6d81ab11b5
    password: 6896ccd0-1da3-4f7f-9908-ba8e0ae64d39
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/user_db
    # username: postgres
    # password: ENC(F8s+vqvqUMoe/Wg3I6A2McDMs7GrKHGV1jn7rP14Qs86wsrqYwGXCyCf0fzzV47h)
    # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

security:
  password:
    secret-key: eBOnOIwn3FL4aKemy4w6Lu9lNy7RD+c0V3iJrajQ1Kw=

jasypt:
  encryptor:
    password: hy6hPm8bstkVHo2iIOnw9u32dnfjnHGD6jbMKB4/flg=
