server:
  port: 9030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: ENC(...)
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update

security:
  password:
    secret-key: ${SECURITY_PASSWORD_SECRET_KEY}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "administrator-service"
    description: "YBank Administrator Service"
