server:
  port: 9060

spring:
  datasource:
    # url: jdbc:postgresql://ssh.basicdeploy.com:5432/bd_u_a4b4f9f7467b?sslmode=disable
    # username: bd_u_a4b4f9f7467b
    # password: ba355ad5-14ad-4caa-9762-af036577881f
    # driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: ENC(F8s+vqvqUMoe/Wg3I6A2McDMs7GrKHGV1jn7rP14Qs86wsrqYwGXCyCf0fzzV47h)
    driver-class-name: org.postgresql.Driver
    hikari:
      # Maximum database connections
      maximum-pool-size: 5

      # Minimum idle connections
      minimum-idle: 1

      # Connection timeout (30 seconds)
      connection-timeout: 30000

      # Close idle connections after 60 seconds
      idle-timeout: 60000

      # Maximum lifetime of a connection (30 minutes)
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    password: hy6hPm8bstkVHo2iIOnw9u32dnfjnHGD6jbMKB4/flg=

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "hotel-service"
    description: "YBank Hotel Service"
